# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-10 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='\u6807\u9898', max_length=1000, null=True)),
                ('type', models.CharField(choices=[('0', '\u539f\u521b'), ('1', '\u8f6c\u53d1'), ('2', '\u7ffb\u8bd1')], max_length=50)),
                ('status', models.CharField(choices=[('draft', '\u8349\u7a3f'), ('on_line', '\u5728\u7ebf'), ('out_line', '\u4e0b\u7ebf')], help_text='\u72b6\u6001', max_length=50)),
                ('classify', models.CharField(help_text='\u5206\u7c7b', max_length=100)),
                ('custom_classify', models.CharField(help_text='\u81ea\u5b9a\u4e49\u5206\u7c7b', max_length=100)),
                ('gmt_create', models.DateTimeField(auto_now_add=True, help_text='\u521b\u5efa\u65f6\u95f4')),
                ('gmt_modified', models.DateTimeField(help_text='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'db_table': 'blog_article',
            },
        ),
        migrations.CreateModel(
            name='BlogArticleContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content_text', models.TextField(help_text='\u6587\u672c\u5185\u5bb9')),
                ('gmt_create', models.DateTimeField(auto_now_add=True, help_text='\u521b\u5efa\u65f6\u95f4')),
                ('gmt_modified', models.DateTimeField(help_text='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'db_table': 'blog_article_content',
            },
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='content_id',
            field=models.ForeignKey(help_text='\u5173\u8054\u5185\u5bb9\u8868id', on_delete=django.db.models.deletion.CASCADE, to='blog.BlogArticleContent'),
        ),
    ]
